smarc-project/SMARCAssets

Runtime/Scripts/VehicleComponents/Sensors/SSS.cs
=> Removed articulation body from SSS components

Runtime/Scripts/VehicleComponents/ROS/Publishers/ActuatorPublisher.cs, Runtime/Scripts/VehicleComponents/ROS/Publishers/SensorPublisher.cs, Runtime/Scripts/VehicleComponents/ROS/Publishers/TF/ROSTransformTreePublisher.cs, Runtime/Scripts/VehicleComponents/Sensors/Sensor.cs
A sensor cant go faster than the physics update rate of Unity itself...
=> Added validation to physics-related frequencies. 

Runtime/Scripts/VehicleComponents/ROS/Subscribers/Teleporter_Sub.cs, Runtime/Scripts/VehicleComponents/ROS/Subscribers/Teleporter_Sub.cs.meta
Convenient for when someone wants to re-try entire missions without restarting the game :)
Just add to any object and assign the thing to teleport. Works in local coordinates.
*cough*RL*cough*
=> New: Teleporter_Sub. Teleport objects in game via ros message

Runtime/Scripts/VehicleComponents/ROS/Publishers/test_pub.cs
In service of: https://github.com/smarc-project/smarc2/issues/35
=> Delay measurements

Runtime/Prefabs/sam_auv_v1.prefab, Runtime/Scripts/VehicleComponents/Acoustics/Transceiver.cs, Runtime/URDF/sam_auv/sam_auv.urdf
Receive time is now send time + calculated delay, rather than "simulation now".
WaitForSeconds is not accurate enough to rely on for this kind of stuff.
=> Transceiver fix and links for front/aft

Runtime/Scripts/VehicleComponents/ROS/Subscribers/Teleporter_Sub.cs
It now works with one message proper.
#47
=> Fix: Teleporter sub now spends one fixed update immovable.

Documentation/README.md
- Updated missing documentation error from updating messages
- Provided info on how to fix LSP errors in text editors (including VSCode) for missing SDK
=> Documentation update

Runtime/Prefabs/Evolo.prefab, Runtime/Scripts/Evolo/EvoloBehaviourScript.cs
I think the IMU works now? Needs to be tested by Alex
=> Evolo: fixed TF, IMU and Lidars. Did some cleanup on the Behaviour script

Runtime/Scripts/Drone/DroneController.cs
Added a new Mode for Controller to get the Velocity & Acceleration from the ML Agent
=> Added VelocityControl for ML Agent

Runtime/Scripts/Drone/DroneController.cs
Bye bye acceleration public control. Forced zeros in all control states.
=> Removing Accel Control

Runtime/Scripts/GeoRef/GlobalReferencePoint.cs, Runtime/Scripts/SmarcGUI/Connections/WaspCommands.cs, Runtime/Scripts/SmarcGUI/Connections/WaspDirectExecutionInfo.cs, Runtime/Scripts/SmarcGUI/MissionPlanning/MissionPlanStore.cs, Runtime/Scripts/SmarcGUI/MissionPlanning/Tasks/TSTGUI.cs, Runtime/Scripts/SmarcGUI/MissionPlanning/Tasks/TaskGUI.cs, Runtime/Scripts/SmarcGUI/RobotGUI.cs
- Waraps field names
- Hotfixes for loading-on-start of missionplans
- Less spam
=> Evolodebug

Runtime/Prefabs/SmarcGUI/GUI.prefab, Runtime/Prefabs/SmarcGUI/Robot/ExecTaskPrefab.prefab, Runtime/Prefabs/SmarcGUI/Robot/RobotGUIPrefab.prefab, Runtime/Scripts/SmarcGUI/Connections/WaspDirectExecutionInfo.cs, Runtime/Scripts/SmarcGUI/RobotGUI.cs, Runtime/Scripts/SmarcGUI/WorldSpace/FixedGlobalRotation.cs, Runtime/Scripts/SmarcGUI/WorldSpace/FixedGlobalRotation.cs.meta
=> Added default abort signal to unknown tasks executed by vehicle.

Runtime/Scripts/Force/ForcePoint.cs, Runtime/Scripts/VehicleComponents/ROS/Publishers/Odometry_Pub.cs, Runtime/Scripts/VehicleComponents/ROS/Subscribers/Teleporter_Sub.cs
And some debugging for the (once thought to be a quick hack that wouldn't need to stay) Teleporter_Sub.
I guess it stays now :D
=> Force point submersion + Teleporter_Sub

Runtime/Prefabs/SmarcGUI/GUI.prefab, Runtime/Prefabs/SmarcGUI/InputSystem_Actions.inputactions, Runtime/Scripts/SmarcGUI/Connections/MQTTClientGUI.cs, Runtime/Scripts/SmarcGUI/Connections/ROSClientGUI.cs, Runtime/Scripts/SmarcGUI/GUIState.cs, Runtime/Scripts/SmarcGUI/RobotGUI.cs, Runtime/Scripts/SmarcGUI/RobotGUIOverlay.cs, Runtime/Scripts/SmarcGUI/WorldSpace/DragZoomCamera.cs, Runtime/Scripts/SmarcGUI/WorldSpace/DragZoomCamera.cs.meta
- Some general improvements to the GUI.
- Added top-down orthographic camera with click-to-drag and scroll-to-zoom motions
- Compass is now on the top bar, as a value (for now)
=> Gui improvements

Runtime/Scripts/SmarcGUI/Connections/MQTTClientGUI.cs, Runtime/Scripts/SmarcGUI/Connections/ROSClientGUI.cs, Runtime/Scripts/SmarcGUI/GUIState.cs, Runtime/Scripts/SmarcGUI/MissionPlanning/MissionPlanStore.cs
MQTT and ROS connection settings can now be saved to file and will be read on start. Defaults are created if no file is found so you know what you can fill in ;)
=> Settings files

LICENSE.meta, Runtime/Prefabs/Quadrotor.prefab, Runtime/Scripts/Drone/DroneController.cs, Runtime/Scripts/SmarcGUI/KeyboardControllers/DroneKeyboardController.cs
WASD now moves the drone target around relative go base link, instead of setting props. So now it works more like commerical drones ;)
=> Drone control QOL

Runtime/Scripts/Drone/Perching Trajectory.cs, Runtime/Scripts/Drone/Perching Trajectory.cs.meta
Set: 
- Controller Mode: Tracking Control 
- Drone Position: a little bit far from the SAM (for example at (1310,4,1165)) position to make sure the drone does not crash before starting 
- Inside DroneTarget, [Perching Trajectory] target: RopeSegment_14 (or anything in the middle)
- Inside DroneTarget, Uncheck UFO script 
Hopefully, the drone will catch the rope.
=> Perching Trajectory

Runtime/Scripts/SmarcGUI/Connections/WaspHeartbeat.cs, Runtime/Scripts/SmarcGUI/RobotGUIOverlay.cs, Runtime/Scripts/VehicleComponents/ROS/Publishers/ActuatorFeedbacks/PercentageFeedback_Pub.cs, Runtime/Scripts/VehicleComponents/ROS/Subscribers/PercentageCommand_Sub.cs
=> Percentage stuff

Runtime/Prefabs/Environment/ForceFields/MeshForceField.prefab, Runtime/Prefabs/Environment/ForceFields/MeshForceField.prefab.meta
=> prefab for the MeshForceField

Runtime/Prefabs/Environment/KTH Tank/KTHTank World.prefab
The tank is now a """robot""", and publishes to `/tf` points on itself.
=> Added TF Publisher to the tank prefab.

Runtime/Prefabs/m350_v1.prefab, Runtime/Scripts/ROS/PSDK_ROS2/PsdkFusedPosition.cs, Runtime/Scripts/ROS/PSDK_ROS2/PsdkHomeAltitude.cs, Runtime/Scripts/ROS/PSDK_ROS2/PsdkHomePosition.cs, Runtime/Scripts/ROS/Publishers/Sensors/Battery_Pub.cs, Runtime/Scripts/SmarcGUI/MissionPlanning/MissionPlanStore.cs, Runtime/Scripts/SmarcGUI/MissionPlanning/Params/PrimitiveParamGUI.cs, Runtime/Scripts/SmarcGUI/MissionPlanning/Tasks/AlarsTasks.cs, Runtime/Scripts/SmarcGUI/MissionPlanning/Tasks/Task.cs
And the winch hook is now the same mass as the real thing. 0.3kg
And fixes to psdk topics.
=> Alars tasks, forgotten primitive param handling

Runtime/Prefabs/Components/WinchSystem.prefab, Runtime/Prefabs/m350_v1.prefab, Runtime/Scripts/DJI/DJIController.cs, Runtime/Scripts/ROS/Publishers/Sensors/LoadCell_Pub.cs, Runtime/Scripts/ROS/Publishers/Sensors/LoadCell_Pub.cs.meta, Runtime/Scripts/VehicleComponents/LinkAttachment.cs, Runtime/Scripts/VehicleComponents/Sensors/Battery.cs, Runtime/Scripts/VehicleComponents/Sensors/DVL.cs, Runtime/Scripts/VehicleComponents/Sensors/DepthPressure.cs, Runtime/Scripts/VehicleComponents/Sensors/GPS.cs, Runtime/Scripts/VehicleComponents/Sensors/Leak.cs, Runtime/Scripts/VehicleComponents/Sensors/LoadCell.cs, Runtime/Scripts/VehicleComponents/Sensors/LoadCell.cs.meta, Runtime/Scripts/VehicleComponents/Sensors/LockedDirectionDepthSensor.cs, Runtime/Scripts/VehicleComponents/Sensors/RangeReciever.cs
- some alars stuff.
- and some small cleanup of imports.
=> Load cell sensor
